name: Build Docker Image

on:
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Echo Docker version
        run: docker version
